import { MigrationInterface, QueryRunner } from "typeorm";

export class FakeMovies1604845106384 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`
        insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Private Fears in Public Places (Coeurs)', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 6, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Polarised impactful customer loyalty', 1, '2020-07-23T00:52:57Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Cencoroll', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 7, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Re-engineered 24/7 knowledge base', 1, '2020-03-31T00:49:48Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Gendarme Gets Married, The (Le gendarme se marie)', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 3, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Visionary zero administration attitude', 1, '2020-05-09T15:46:17Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Garage Olimpo', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 3, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Virtual 5th generation policy', 1, '2020-06-03T11:23:14Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('12 Storeys (Shier lou)', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 9, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Ergonomic bi-directional extranet', 1, '2020-03-29T07:22:54Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Dancer, Texas Pop. 81', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 9, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Focused full-range moderator', 1, '2020-05-14T04:31:59Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('The Elephant Man', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 9, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Automated clear-thinking adapter', 1, '2020-06-16T00:33:18Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('God Who Wasn''t There, The', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 7, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Horizontal executive attitude', 1, '2020-01-07T00:45:34Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Ennui, L''', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 6, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Assimilated content-based core', 1, '2020-09-04T08:34:10Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Last Supper, The', 'Aenean sit amet justo. Morbi ut odio.', 9, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Team-oriented tertiary paradigm', 1, '2020-02-09T02:48:17Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Rentun Ruusu', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 8, 'http://dummyimage.com/960x540.png/dddddd/000000', 'Streamlined local instruction set', 1, '2020-07-31T13:23:41Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Caroline?', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Team-oriented tertiary challenge', 1, '2019-11-22T00:14:45Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Carabineers, The (Carabiniers, Les)', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 6, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Triple-buffered mobile structure', 1, '2020-07-14T12:39:17Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Birdemic: Shock and Terror', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 5, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Realigned attitude-oriented parallelism', 1, '2020-03-27T00:40:51Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('I''ll Follow You Down', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 1, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Streamlined user-facing architecture', 1, '2020-05-10T17:24:55Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Johnny Skidmarks', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 5, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Focused explicit moratorium', 1, '2020-09-09T11:53:40Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Christmas Toy, The', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 10, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Optional hybrid strategy', 1, '2020-07-26T12:06:32Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('June 9 ', 'Nulla justo.', 8, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Monitored bottom-line secured line', 1, '2020-05-10T05:19:57Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Import/Export', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 8, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Public-key motivating core', 1, '2020-09-10T04:03:37Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Shock', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 6, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Face to face tertiary projection', 1, '2020-02-12T16:45:48Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Paramore Live, the Final Riot!', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 1, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Streamlined empowering model', 1, '2020-04-14T15:53:52Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Off Beat', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 5, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Integrated user-facing contingency', 1, '2020-01-25T20:22:40Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Still Crazy', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 1, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Focused content-based model', 1, '2020-06-01T15:45:59Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Tumannost Andromedy', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 4, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'User-centric human-resource paradigm', 1, '2020-06-06T20:28:28Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Event, The', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 7, 'http://dummyimage.com/960x540.png/ff4444/ffffff', 'Synergized heuristic alliance', 1, '2020-05-18T01:28:05Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Getting Any? (Minnâ-yatteruka!)', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 5, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Automated demand-driven matrices', 1, '2020-01-11T13:26:24Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Shall We Dance', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 8, 'http://dummyimage.com/960x540.png/cc0000/ffffff', 'Managed grid-enabled help-desk', 1, '2020-06-15T21:11:17Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Watchmen: Tales of the Black Freighter', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 1, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Synergistic systematic model', 1, '2020-01-21T03:36:51Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Deadly Friend', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 3, 'http://dummyimage.com/960x540.png/dddddd/000000', 'Exclusive tangible intranet', 1, '2020-06-15T04:33:29Z');
insert into movie (title, description, rating, poster, reason, "creatorId", "createdAt") values ('Bourne Identity, The', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 4, 'http://dummyimage.com/960x540.png/5fa2dd/ffffff', 'Up-sized reciprocal portal', 1, '2020-09-04T08:10:05Z');`);
    }

    public async down(_: QueryRunner): Promise<void> {}
}
